[Main]
LogLevel=1
ocrengine=0
blackcard=0
WaitCardIn=0
WaitCardOut=0

#扫描图片
ShowPicture=0
IfDeletePic_cp=0

#demo页面
ifTestOwn =0
ifSetCIS =0
ifUseCPU =1

#卡片方向
CardDirection = 1
SaveAllPicture = 1

#读DG
#0 = 底层读，1 = 上层读
ReadDGInfo=1

[IMG]
corner = 1
radius = 40
guohui = 1
X = 5;

[Device]
Pid = 5710
Vid = 0483

[Encoding]
# 0 = GBK ; 1 = UTF-8
Encoding = 0

[Test]
Time=1000
ReadID=1
ScanPicture=1
SleepTime=200
ScanTypeTime = 1

#7005B
[cutImgB]
ytop= 5
ybutton= 15

#社保卡
[SocialCard]
Type=ICBC
ConstRect=0

#建设银行
[CCB]
x=180
y=445
width=740
height=70

#中国工商银行
[ICBC]
x=180
y=445
width=740
height=70

#招商银行
[CMC]
x=165
y=430
width=700
height=70

#身份证头像
[IDHEAD]
x=570
y=90
width=290
height=380