[Main]
#1  调试信息及记录全部日志
#2  提示信息及记录警告、错误日志
#3  警告信息及记录错误日志
#4  错误信息
#5  不记录日志
LogLevel=2
ControlDisp=1

logLevel=1
DeleteLogTime=5

ocrengine=0
timeout=8000
#测试程序日志
TestLog=1

#显示图片，显示时会暂停
ShowPic=0

#扫描图片
#=2不裁剪；=3其他算法；4=卓识
CutMode=4

#人脸识别
#=0使用老算法；=1其他算法
FaceMode=1

#FaceMode=1时，检测人脸标注图片是否保存
#=0不保存；=1保存
FaceCheckSave=0

#保存原图（扫描时的原图）
SaveOriginalPicture = 0
#保存旋正裁剪后图片
SavePicture = 0

#PCSC读卡器
#PCSCReader=CREATOR CRT-603 (CZ1) CCR RF 0
PCSCReader=Mobile-ID CheckID-SR V2 0

#读DG
#0 = 底层读，1 = 上层读
ReadDGInfo=0

#Ocr识别方法
#=0原算法；=1卓识
OcrMode=1

#MRZ使用图片二值化(7201不需要)--OcrMode=0有效
#=1二值化；=0不二值化	
OcrThresh=1

#Ocr识别后抠图图片是否删除--OcrMode=0有效
#=1删除；=0不删除	
OcrCutDel=0

#Ocr识别后二值化图图片是否删除--OcrMode=0有效
#=1删除；=0不删除	
OcrThreshDel=0

#Ocr识别文件是否删除--OcrMode=0有效
#=1删除；=0不删除	
OcrocrDel=0

#默认ocr方法失败后是否使用pp ocr
#=0不使用；=1使用		
PPOcr=0

[IMG]
corner = 0
radius = 40
guohui = 1
X = 5

[Encoding]
# 0 = GBK ; 1 = UTF-8
Encoding = 0

[Command]
send1=4360304142
send3=4336313037
send2=434A4201

[Picture_Front]
#原图保存：
#=0不保存，此时brightness\contrast\gamma\saturation\redAdjust\greenAdjustblueAdjust有效
#=1保存，此时brightness\contrast\gamma\saturation\redAdjust\greenAdjustblueAdjust无效
Originalpicture=0
#亮度调整值，范围[-255,255]
brightness=0
#对比度调整值，范围[-127,127]
contrast=-5
#Gamma校正值，范围[0.01,6.99]
gamma=110
#饱和度调整值，范围[-255, 255]
saturation=0
#红色通道调整值，范围[-255, 255]
redAdjust=-10
#绿色通道调整值，范围[-255, 255]
greenAdjust=0
#蓝色通道调整值，范围[-255, 255]
blueAdjust=15

[Picture_Back]
#原图保存：
#=0不保存，此时brightness\contrast\gamma\saturation\redAdjust\greenAdjustblueAdjust有效
#=1保存，此时brightness\contrast\gamma\saturation\redAdjust\greenAdjustblueAdjust无效
Originalpicture=0
#亮度调整值，范围[-255,255]
brightness=0
#对比度调整值，范围[-127,127]
contrast=-5
#Gamma校正值，范围[0.01,6.99]
gamma=110
#饱和度调整值，范围[-255, 255]
saturation=0
#红色通道调整值，范围[-255, 255]
redAdjust=-10
#绿色通道调整值，范围[-255, 255]
greenAdjust=0
#蓝色通道调整值，范围[-255, 255]
blueAdjust=15

[Test]
SleepTime=500
